name: build
on:
  push:
    branches:
      - main
jobs: 
  my_job: 
    build:
      runs-on: ubuntu-latest
      steps:
      - name: check code
        uses: actions/checkout@v3
       
      - name: login
     
       
       
      
          
      
    
